### PR TITLE
Add implementation of merge sort algorithm

### PR DESCRIPTION
**Pull request by frymash**
## Checklist

- [X] I read the [contributing guidelines](./CONTRIBUTING.md) and the [code of conduct](./CODE_OF_CONDUCT.md)
- [X] If I committed a file, it is written in the Racket language.
- [X] My pull request is not spam and is useful to the repository

### CODE REVIEW

**Comment by Bobliuuu** [comment]
@ozervesh Please implement merge sort correctly. There is no file committed currently.

**Review by Bobliuuu — CHANGES_REQUESTED** [review]
Please add merge sort algorithm back so it can be reviewed.

**Comment by frymash** [comment]
Hi Bobliuuu, I'd removed the merge-sort.rkt~ temp file earlier (7d9a4ed) but the merge-sort.rkt file is still present in this PR from my end. 

Is the.rkt file not viewable from your side? I'll try to re-commit it if that's the case. Thanks!

**Review by Bobliuuu — APPROVED** [review]

**Comment by Bobliuuu** [comment]
Hi @ozervesh, thanks for clarifying! LGTM

**Pull request merged**
